### ISSUE TITLE
A more detail tutorial

### ISSUE THREAD

**Issue by GabrielLin** [IBM/science-result-extractor#2]
After the model has been trained and PDF files have been downloaded. How can I use the trained model to extract information on PDF files? Thanks.

**Comment by yufanghou** [comment]
Hi @abrielLin, ```GenerateTestDataOnPDFPapers``` provides methods to generate testing dataset for any PDF papers, you could apply the trained model on these testing data instances and extract information. Suppose you want to extract TDM triples, so for each testing PDF file, you need to provide the testing TDM hypotheses, this could come from the training data, or any other valid TDM triples which are likely related to the corresponding paper (See Section 7 Zero-shot TDM Classification).

**Comment by GabrielLin** [comment]
@yufanghou  Thanks for your rapid reply. I will have a try.

**Comment by GabrielLin** [comment]
Dear @yufanghou  Sorry for a long gap for feedback since I am distracted by other matters. 

I downloaded 6 PDF files from ACL, EMNLP and NAACL 2019 and managed to generate `test.tsv` and `test_score.tsv`.

Then, I used the trained model to predict the `test.tsv`. The generated results are something like
```
0.0042572664	0.99574274
0.004257262	0.99574274
0.004257234	0.99574274
0.0042572706	0.99574274
0.0042572417	0.99574274
0.0042573325	0.9957426
0.0042572585	0.99574274
0.0042572953	0.99574274
0.0042573307	0.9957426
0.0042572767	0.99574274
0.0042572827	0.99574274
0.0042572706	0.99574274
0.004257329	0.9957426
0.004257275	0.99574274
0.004257329	0.9957426
0.0042573386	0.9957426
0.0042572785	0.99574274
0.0042572664	0.99574274
0.0042572827	0.99574274
0.004257252	0.99574274
0.0042572482	0.99574274
0.00425725	0.99574274
0.00425724	0.99574274
0.004257246	0.99574274
0.0042572888	0.99574274
0.0042572664	0.99574274
0.0042572706	0.99574274
0.0042572985	0.9957426
0.0042573027	0.9957426
0.00425724	0.99574274
0.0042572953	0.99574274
0.0042572604	0.99574274
0.0042574145	0.9957426
0.004257262	0.99574274
0.0042573228	0.9957426
0.0042572664	0.99574274
0.004257246	0.99574274
0.004257291	0.99574274
0.0042572953	0.99574274
0.0042572664	0.99574274
0.004257262	0.99574274
0.0042572543	0.99574274
0.0042572664	0.99574274
0.004257262	0.99574274
0.0042572706	0.99574274
0.0042572827	0.99574274
0.004257275	0.99574274
0.004257262	0.99574274
0.0042572888	0.99574274
0.0042572664	0.99574274
0.004257275	0.99574274
0.004257238	0.99574274
0.0042572888	0.99574274
0.0042572864	0.99574274
```

Which are similar to your `https://github.com/IBM/science-result-extractor/blob/master/data/exp/few-shot-setup/NLP-TDMS/test_results.tsv`. 

My question is why the left side probabilities are always small and the right side probabilities are always big. It seems that the predictions are only one value. I suppose the predictions should be some True and some False. 

Thanks.

**Comment by GabrielLin** [comment]
Another question is that the default setting of `run_classifier_sci.py` seems to deal with the `DocTAET-TDM model`. How to change the setting for `SC-DM model`. Do I miss something? Thanks.

**Comment by yufanghou** [comment]
Hi @GabrieLin, regarding the uniform probabilities you've seen in the results, some people had the similar issues before and they found that increasing the batch size from 6 to 11 and freezing the parameters of 0-6 layers works. Maybe try to train the model again with bigger batch size? 

For the second question above, the model SC-DM is trained the same way as DocTAET-TDM model, in the final inference stage, TEModelEvalOnNLPTDMS class combines the predictions from these two models and forms TDMS tuples for each paper.

**Comment by GabrielLin** [comment]
@yufanghou Thanks. Let me try to train it with your suggestions.
