### ISSUE TITLE
Flair-TDM and TDM Knowledge Graph

### ISSUE THREAD

**Issue by GabrielLin** [IBM/science-result-extractor#5]
Could you please share the code of Flair-TDM and way to construct TDM Knowledge Graph mentioned at Hou, Y., Jochim, C., Gleize, M., Bonin, F., & Ganguly, D. (2021, apr). TDMSci: A Specialized Corpus for Scientific Literature Entity Tagging of Tasks Datasets and Metrics, Online.? Really thanks.

**Comment by yufanghou** [comment]
Hi @GabrielLin, I put an illustrative training script under /data/TDMSci/modelTrainingScript, you need to adjust the data dir and model dir. Also before running the script, you need to install Flair. A more comprehensive tutorial about Flair can be found here https://github.com/flairNLP/flair. 

Regarding the TDM knowledge graph, recently we had a paper accepted at ACL2021 Findings: "End-to-End Construction of NLP Knowledge Graph". The paper proposed a more advanced method to build the knowledge graph mentioned in the EACL21 paper. Code and the built KG will be open sourced soon after we finish the camera-ready version.

**Comment by GabrielLin** [comment]
Thank you @yufanghou . How amazing the work is. I am eager to see that paper and code. Will the paper be placed at arXiv?

**Comment by yufanghou** [comment]
Hi @GabrielLin, thanks for your interests. At the moment we are in the working process to prepare the final version. We do plan to put the final version on arXiv. I'll let you know when it's ready.

**Comment by GabrielLin** [comment]
Got it. I am looking forward to it.
