### ISSUE TITLE
Flair-TDM Model setup?

### ISSUE THREAD

**Issue by logan-markewich** [IBM/science-result-extractor#8]
Hi! Thanks for this great work!

I am trying to replicate some of your results for my own publication. Do you still have the code for the Flair model?

As you know, there are many ways to configure the model embeddings. I'm just curious what your setup was.

Thanks!
![image](https://user-images.githubusercontent.com/22285038/214468085-d9331f2c-f755-4f17-9ba3-99f05449ed71.png)

**Comment by yufanghou** [comment]
Hi @logan-markewich, for the embeddings, the combination of glove + news-forward + news-backward should give you a decent performance. Other parameters are the same as your setup except that I use 150 for max_epochs.

-- Yufang

**Comment by logan-markewich** [comment]
I will give that a shot, thanks so much!

And thanks for getting back to me, even though the project is a little older 🙏🏻
